spring:
  application:
    name: config-service
  cloud:
    bus:
      id: my-config-server
      enabled: true
      refresh:
        enabled: true
    stream:
      kafka:
        binder:
          zkNodes: zookeeper-service:2181
          brokers: kafka-service:9092
    config:
      server:
        git:
          # URI of GIT repo containing properties
          uri: https://github.com/srirajkondapuli/simple-gateway
          default-label: main
          search-paths: configuration
server:
  port: 8888
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
